version: '2.1'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    privileged: true
    ports:
      - "4566-4599:4566-4599"
      - "9070:9070"
    environment:
      SERVICES: sqs, rds, ec2, kinesis, iam, lambda, dynamodb, apigateway, s3, sns, cloudformation, cloudwatch, stepfunctions
      DOCKER_HOST: unix:///var/run/docker.sock
      PORT_WEB_UI: 9070
      LAMBDA_EXECUTOR: docker
      DEBUG: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/localstack:/tmp/localstack